# Generated by Django 3.2.9 on 2021-11-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='dealerMail',
        ),
    ]
